### ISSUE TITLE
Move unit tests over from heritrix3 to webarchive-commons

### ISSUE THREAD

**Issue by kris-sigur** [iipc/webarchive-commons#25]
After @nlevitt moved over the code needed from Heritrix3 (iipc/iipc-web-commons@fc24be82f632abd7ca56337be77b7ee683368338, iipc/iipc-web-commons@a54dd8eb11b13988a64fed9f0a1e94faf80dc03e), but not the unit tests. They should be moved over before release.

**Comment by MohammedElsayyed** [comment]
Regarding iipc/iipc-web-commons@fc24be82f632abd7ca56337be77b7ee683368338, it contains PublicSuffixesTest.java unit test, should I take it into consideration?

Regarding iipc/iipc-web-commons@a54dd8eb11b13988a64fed9f0a1e94faf80dc03e, not all files have their corresponding unit tests in [Heritrix3](https://github.com/iipc/heritrix3). Only 17 files as shown below:

/commons/src/test/java/org/archive/io/arc/ARCReaderFactoryTest.java
/commons/src/test/java/org/archive/io/arc/ARCWriterPoolTest.java
/commons/src/test/java/org/archive/io/arc/ARCWriterTest.java
/commons/src/test/java/org/archive/io/ArchiveReaderFactoryTest.java
/commons/src/test/java/org/archive/io/BufferedSeekInputStreamTest.java
/commons/src/test/java/org/archive/io/HeaderedArchiveRecordTest.java
/commons/src/test/java/org/archive/io/RecordingInputStreamTest.java
/commons/src/test/java/org/archive/io/ReplayCharSequenceTest.java
/commons/src/test/java/org/archive/io/RepositionableInputStreamTest.java
/commons/src/test/java/org/archive/io/warc/WARCWriterTest.java
/commons/src/test/java/org/archive/uid/UUIDGeneratorTest.java
/commons/src/test/java/org/archive/util/anvl/ANVLRecordTest.java
/commons/src/test/java/org/archive/util/FileUtilsTest.java
/commons/src/test/java/org/archive/util/MimetypeUtilsTest.java
/commons/src/test/java/org/archive/util/PropertyUtilsTest.java
/modules/src/test/java/org/archive/modules/writer/ARCWriterProcessorTest.java
/modules/src/test/java/org/archive/modules/writer/WARCWriterProcessorTest.java

Should I just move unit tests listed above from [Heritrix3](https://github.com/iipc/heritrix3) to [webarchive-commons](https://github.com/iipc/webarchive-commons) or is there something else I should include?

**Comment by ldko** [comment]
Hi Mohamed, we want to bring over from Heritrix3 any tests that exist for the files moved over in  iipc/iipc-web-commons@a54dd8eb11b13988a64fed9f0a1e94faf80dc03e. Since the PublicSuffixesTest.java was brought over to webarchive-commons in the other commit you mentioned, we don't need to worry about that one. I don't think we will need to bring over these two you listed:
```
/modules/src/test/java/org/archive/modules/writer/ARCWriterProcessorTest.java
/modules/src/test/java/org/archive/modules/writer/WARCWriterProcessorTest.java
```

**Comment by nlevitt** [comment]
Do you mind also submitting a PR to heritrix to remove the (now redundant) tests from there?
