### ISSUE TITLE
Minor issues with the POM

### ISSUE THREAD

**Issue by anjackson** [iipc/webarchive-commons#3]
There is no organization tag.

I wonder if we should explicitly declare this a Maven 3 project? It already conforms to M3.

The compiler plugin specifies Java 6. Seems like a good time to bump this up to 7.

I notice that there is an assembly plugin defined to create a "jar-with-dependencies". This doesn't seem necessary or useful for a library.

**Comment by RogerMathisen** [comment]
Seems all requests in this issue either are fixed or moved to new issues under the 1.2.0 release, closing.
