### ISSUE TITLE
RecordingOutputStream can affect tcp packets sent in an undesirable way

### ISSUE THREAD

**Issue by nlevitt** [iipc/webarchive-commons#38]
Looking at a heritrix request with tcpdump, you can see that a separate tcp packet is sent for each of the characters 'G' 'E' 'T' ' ' '/' ' ' 'H' 'T' 'T'... at the beginning of each http request. We ran into a website that responds with a 400 to these requests. Besides, it's inefficient and ugly to be sending all these little packets. The culprit is a shortcut in my own code in RecordingOutputStream.

**Comment by nlevitt** [comment]
Pull request https://github.com/iipc/webarchive-commons/pull/39

Also since this pull request moves RecordingOutputStreamTest.java in webarchive-commons, a pull request to remove it from heritrix:
https://github.com/internetarchive/heritrix3/pull/114

**Comment by anjackson** [comment]
Also rolled a release, so this fix should be in [1.1.5](http://search.maven.org/#artifactdetails|org.netpreserve.commons|webarchive-commons|1.1.5|jar)

**Comment by nlevitt** [comment]
Thank you for rolling this release promptly, now heritrix doesn't have to have -SNAPSHOT dependency!
