### ISSUE TITLE
Require Java 8

### ISSUE THREAD

**Issue by johnerikhalse** [iipc/webarchive-commons#56]
As of April 2016, Java 7 has reached its end of public updates.

We should move to Java 8 both for this reason and to be able to utilize enhancements in the language and libraries. For example would the new date and time classes fit our needs.

The implication is that this will spread to Heritrix and OpenWayback when they decide to update their webarchive-commons dependency.

This change should probably go into a major release.

**Comment by ato** [comment]
Completed in b389fe5b3b880f9eeb7a6b3612a91724ad968347
