### ISSUE TITLE
support WET files

### ISSUE THREAD

**Issue by dportabella** [iipc/webarchive-commons#66]
CommonCrawl has the [WET files](http://commoncrawl.org/the-data/get-started/), which are WARC files where HTML response has been converted to plain text (and non html pages has been removed).

Is it possible to support WET files with webarchive-commons?

or shall I implement this feature (to handle WET archives)?

is this a feature that you would include in the webarchive-commons library?

do you see any shortcoming/problem/comment on this?

**Comment by anjackson** [comment]
I'm pretty sure a WET is just a WARC file, but with 'conversion' records that contain text/plain. So, parsing WET files is already supported, at least in terms of basic parsing.

Looking at https://github.com/lintool/warcbase/issues/250 and tracking down the RecordLoader it [looks like that is automatically filtering out anything other than 'response' records](https://github.com/lintool/warcbase/blob/8ba16e842c299c2955bedb1062b3ed8f1aa95190/warcbase-core/src/main/scala/org/warcbase/spark/matchbox/RecordLoader.scala#L37).  If that was made configurable so you could change it to access conversion records, I think you're all set.

**Comment by kris-sigur** [comment]
+1 to Andy's comments. Any 'deeper' or more advanced processing of WET files probably belong in a dedicated 'WET library'.

**Comment by dportabella** [comment]
cool! I just told the warcbase guys about this.
https://github.com/lintool/warcbase/issues/250#issuecomment-250478304
